//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayCalc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayCalc.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYCALC.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calculate.
        /// </summary>
        public static string CalcButtonText {
            get {
                return ResourceManager.GetString("CalcButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calculate.
        /// </summary>
        public static string CalculationPageName {
            get {
                return ResourceManager.GetString("CalculationPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductions.
        /// </summary>
        public static string DeductionsBlockText {
            get {
                return ResourceManager.GetString("DeductionsBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string DetailsPageName {
            get {
                return ResourceManager.GetString("DetailsPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hourly pay.
        /// </summary>
        public static string HourlyPayBlockText {
            get {
                return ResourceManager.GetString("HourlyPayBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours worked.
        /// </summary>
        public static string HoursTextBlock {
            get {
                return ResourceManager.GetString("HoursTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string IncomeBlockText {
            get {
                return ResourceManager.GetString("IncomeBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to net pay per hour:.
        /// </summary>
        public static string payBlockText {
            get {
                return ResourceManager.GetString("payBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retirement payment.
        /// </summary>
        public static string RetirementBlockText {
            get {
                return ResourceManager.GetString("RetirementBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tax deduction %.
        /// </summary>
        public static string TaxDeductionsBlockText {
            get {
                return ResourceManager.GetString("TaxDeductionsBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total net pay:.
        /// </summary>
        public static string TotalNetPayBlockText {
            get {
                return ResourceManager.GetString("TotalNetPayBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unemployment payment.
        /// </summary>
        public static string UnemploymentBlockText {
            get {
                return ResourceManager.GetString("UnemploymentBlockText", resourceCulture);
            }
        }
    }
}
